export const relocationTableSchemas = [
  {
    table: 'relocategh_family_members',
    columns: [
      'id uuid primary key',
      'full_name text not null',
      'relationship text not null',
      'date_of_birth date',
      'notes text',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
  {
    table: 'relocategh_documents',
    columns: [
      'id uuid primary key',
      'family_member_id uuid references relocategh_family_members(id)',
      'document_type text not null',
      'status text not null',
      'issue_date date',
      'expiry_date date',
      'reference_number text',
      'original_available boolean default false',
      'copy_available boolean default false',
      'notes text',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
  {
    table: 'relocategh_timeline_tasks',
    columns: [
      'id uuid primary key',
      'title text not null',
      'category text not null',
      'due_date date',
      'status text not null',
      'priority text not null',
      'assigned_family_member_id uuid references relocategh_family_members(id)',
      'notes text',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
  {
    table: 'relocategh_shipping_quotes',
    columns: [
      'id uuid primary key',
      'company_name text not null',
      'contact_name text',
      'phone text',
      'email text',
      'quote_amount numeric(12,2)',
      'currency text',
      'collection_date date',
      'estimated_delivery_date date',
      'shipment_type text',
      'included_services text',
      'insurance_included boolean default false',
      'notes text',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
  {
    table: 'relocategh_housing_options',
    columns: [
      'id uuid primary key',
      'property_title text not null',
      'rent numeric(12,2)',
      'currency text',
      'location text',
      'postcode text',
      'number_of_rooms int',
      'advert_link text',
      'landlord_or_agent_name text',
      'contact_details text',
      'deposit_amount numeric(12,2)',
      'furnished_status text',
      'distance_to_school text',
      'distance_to_hospital text',
      'viewed boolean default false',
      'shortlisted boolean default false',
      'decision_status text',
      'notes text',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
  {
    table: 'relocategh_inventory_rooms',
    columns: [
      'id uuid primary key',
      'room_name text not null',
      'sort_order int default 0',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
  {
    table: 'relocategh_inventory_items',
    columns: [
      'id uuid primary key',
      'room_id uuid references relocategh_inventory_rooms(id)',
      'item_name text not null',
      'quantity int default 1',
      'status text not null',
      'notes text',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
  {
    table: 'relocategh_school_entries',
    columns: [
      'id uuid primary key',
      'family_member_id uuid references relocategh_family_members(id)',
      'school_name text not null',
      'address text',
      'contact_name text',
      'contact_details text',
      'fee_per_year numeric(12,2)',
      'application_status text',
      'year_group text',
      'distance_from_home text',
      'notes text',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
  {
    table: 'relocategh_healthcare_entries',
    columns: [
      'id uuid primary key',
      'family_member_id uuid references relocategh_family_members(id)',
      'doctor_name text not null',
      'address text',
      'fee numeric(12,2)',
      'contact_details text',
      'notes text',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
  {
    table: 'relocategh_budget_items',
    columns: [
      'id uuid primary key',
      'category text not null',
      'item_name text not null',
      'planned_cost numeric(12,2)',
      'actual_cost numeric(12,2)',
      'currency text',
      'status text',
      'due_date date',
      'notes text',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
  {
    table: 'relocategh_misc_notes',
    columns: [
      'id uuid primary key',
      'title text not null',
      'category text',
      'note_body text not null',
      'priority text',
      'linked_family_member_id uuid references relocategh_family_members(id)',
      'linked_section text',
      'date_added date',
      'created_at timestamptz default now()',
      'updated_at timestamptz default now()',
    ],
  },
] as const;
